# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: true
    cookie_secure: auto    # Utilise les cookies sécurisés (HTTPS) seulement si le site est en HTTPS
    cookie_httponly: true  # Empêche l'accès aux cookies via JavaScript
    gc_maxlifetime: 3600   # Durée de vie des sessions en secondes (par exemple 1h ici)

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
