# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  product_images_directory: "%kernel.project_dir%/public/uploads/products"
  env(MONGODB_URL): ''
  env(MONGODB_DB): ''
  default_gemini_api_key: ''

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $geminiApiKey: '%env(default:default_gemini_api_key:GOOGLE_GEMINI_API_KEY)%'

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # Ajout des services manquants
  Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface: '@security.token_storage'
  Symfony\Component\HttpFoundation\Session\SessionInterface: '@session'

  App\Service\AiServiceInterface: '@App\Service\GeminiService'

  App\Service\GeminiService:
    arguments:
      $geminiApiKey: '%env(default:default_gemini_api_key:GOOGLE_GEMINI_API_KEY)%'
      $productRepository: '@App\Repository\ProductRepository'
      $reviewRepository: '@App\Repository\ReviewRepository'

  App\Repository\ReviewRepository:
    factory: ['@doctrine_mongodb.odm.default_document_manager', getRepository]
    arguments:
      - 'App\Document\Review'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
